In [ ]:
import pandas as pd
import re
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize, word_tokenize
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
data = pd.read_csv('Treebo.csv')

In [ ]:
data.head()

review_title  stars                          date  \
0     A mediocre place    2.0   Date of stay: December 2021   
1  Not well maintained    1.0   Date of stay: December 2021   
2   Average experience    2.0  Date of stay: September 2021   
3            Traveling    2.0      Date of stay: March 2021   
4        Average hotel    3.0   Date of stay: February 2020   

                                         full_review  
0  Our stay in this place left much to be desired...  
1  The rooms we were given were such that either ...  
2  1) Receptionist at time of check-in was rude. ...  
3  Breakfast  limited menu.  Poor service.  Stay ...  
4  I stayed for one night with family. This is av...

In [ ]:
data['stars'].value_counts()

5.0    25
4.0    22
3.0    13
2.0     8
1.0     6
Name: stars, dtype: int64

In [ ]:
data['stars_int'] = data['stars'].astype(int)

In [ ]:
reviews = data['full_review']

In [ ]:
reviews = list(reviews)

In [ ]:
reviews[:3]

['Cleaning of my room has been done by Anjali..she has been really helpful for all cleaning stuff and really polite and ready to help for anything you asked for..even i had a word with her regarding city ..',
 'Pleasantly surprised , with the quality of staff and the hotel . I experienced more than I had expected . Very professional drivers who received me on arrival and saw me off at departure. Mr Tanishq/ Mayur and the team ever smiling.at the receiption. Mr Shamsudeen and his team at the Kava who took care of my breakfast, but the best was  Ms Anjali , who took care of my laundry and cleaning my room . She was brilliant , I can say I got a brand new room every day for 8 days. Having stayed in all the luxurious hotels in Indore , I can very well say that , this was my best stay because of the service I was rendered and the smiling enthusiastic staff who made my stay memorable. I would highly recommend this hotel , which is centrally located for business or for pleasure. I am already'

In [ ]:
from nltk.tokenize import sent_tokenize, word_tokenize

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
lemmatizer = WordNetLemmatizer()

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [ ]:
def get_wordnet_pos(word):
    """Map POS tag to first character lemmatize() accepts"""
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}

    return tag_dict.get(tag, wordnet.NOUN)

In [ ]:
clean_data_6 = []
for words in clean_data_5:
  clean = []
  for word in words:
    clean.append(lemmatizer.lemmatize(word, get_wordnet_pos(word)))
  clean_data_6.append(clean)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(ngram_range=(1,2))
def vectorize_data(clean_data):
  clean = []
  for data in clean_data:
    vect_data = cv.fit_transform(data).toarray()
    clean.append(vect_data)
  return clean

In [ ]:
cv.transform(x[0]).toarray().reshape((1,-1)).squeeze()

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
cv = CountVectorizer(ngram_range=(1,2))
print(vectorize_data([['siddhant'], ['jain s s ss ']]))

[array([[1]]), array([[1, 1, 1]])]


In [ ]:
def clean_text(data):

  # Converting to lower-case
  clean_data_1 = []
  for review in data:
    clean_data_1.append(review.lower())

  # Converting paragraphs to sentences
  clean_data_2 = []
  for review in clean_data_1:
    clean_data_2.append(sent_tokenize(review))

  # Converting sentences to individual words
  clean_data_3 = [word_tokenize(i) for i in clean_data_1]

  # Removing un-needed unicode characters
  clean_data_4 = []
  for words in clean_data_3:
    clean = []
    for word in words:
      w = re.sub(r'[^\w\s]', "", word)
      if w != "":
        clean.append(w)
    clean_data_4.append(clean)

  # Removing stopwords
  clean_data_5 = []
  for words in clean_data_4:
    clean = []
    for word in words:
      if not word in stopwords.words('english'):
        clean.append(word)
    clean_data_5.append(clean)

  # Lemmatization
  clean_data_6 = []
  for words in clean_data_5:
    clean = []
    for word in words:
      clean.append(lemmatizer.lemmatize(word, get_wordnet_pos(word)))
    string = " ".join(clean)
    clean_data_6.append(string)
  
  return clean_data_6

In [ ]:
x = data['full_review']
y = data['stars_int']

In [ ]:
data.shape

(74, 5)

In [ ]:
x = clean_text(x)

In [ ]:
x

['stay place left much desire due factor 1 staff rigid refuse provide breakfast 800 2 room unkept tidy 3 house keep staff carelessly left unclean bathroom mat bed 4 house keep staff leisurely left packet tabacoo consume room 5 hotel staff remind provide basic item like towel tea bag sugar packet etc contact treebo hotel area representative indore seek solution problem say representative person courtesy listen predicament try resolve grievance',
 'room give either furniture broken dirty lot argument get slightly well room kettle dirty bucket dirty room dint hv telecom overall bad experience',
 '1 receptionist time checkin rude show room incomplete facility ask cancel stay 2 light corridor 2 day 3 telephone line room dead every time go reception 4 post argument get decent room overall experience average',
 'breakfast limited menu poor service stay comfortable covid guideline follow hotel room cleaning good familiar hotel bad smell smoke ventilation entire hotel',
 'stayed one night famil

In [ ]:
cv = CountVectorizer(ngram_range=(1,2))

In [ ]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
cv.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['11pm',
 '11pm repeat',
 '12th',
 '12th jan',
 '14th',
 '14th jan',
 '15',
 '15 min',
 '18',
 '18 percentage',
 '2020',
 '2020 conveniently',
 '2025',
 '2025 min',
 '24',
 '24 hr',
 '28',
 '28 room',
 '30',
 '30 min',
 '3km',
 '3km railway',
 '45',
 '45 hotel',
 '45 minute',
 '45 value',
 '455',
 '455 thing',
 '55',
 '55 km',
 '55 nonetheless',
 '800',
 '800 room',
 '810am',
 '810am arrive',
 '815',
 '815 morning',
 '830',
 '830 miss',
 'aarrangent',
 'aarrangent fine',
 'ac',
 'ac noise',
 'ac water',
 'accept',
 'accept payment',
 'access',
 'access entire',
 'access wifi',
 'accommodate',
 'accommodate great',
 'accomodate',
 'accomodate day',
 'accomodation',
 'accomodation posh',
 'accord',
 'accord postlocation',
 'actually',
 'actually assures',
 'adament',
 'adament staff',
 'add',
 'add breakfast',
 'add confidence',
 'add variety',
 'adult',
 'adult provide',
 'advance',
 'advance otherwise',
 'advance payment',
 'advantage',
 'advantage seem',
 'aesthetic',
 'aesthetic entr

In [ ]:
len(x)

74

In [ ]:
x = np.array(x).reshape((-1, 1))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [ ]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [ ]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
mn = MultinomialNB()

In [ ]:
mn.fit(X_train, y_train)

MultinomialNB()

In [ ]:
y_pred = mn.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test, y_pred)

0.36